# Generated by Django 3.2.8 on 2021-10-25 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basemap', '0001_initial'),
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='basemap',
            field=models.ManyToManyField(to='basemap.BaseMap'),
        ),
    ]
