# Generated by Django 3.2.8 on 2021-10-25 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0003_auto_20211025_1009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='car',
        ),
    ]
