# Generated by Django 3.2.8 on 2021-10-25 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0004_remove_user_car'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='basemap',
        ),
    ]
