# Generated by Django 3.2.8 on 2021-10-26 05:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('basemap', '0002_basemap_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basemap',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='basemap', to=settings.AUTH_USER_MODEL),
        ),
    ]
