# Generated by Django 3.2.8 on 2021-10-31 07:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('basemap', '0006_auto_20211026_1433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basemap',
            name='user',
        ),
        migrations.AddField(
            model_name='basemap',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='basemap', to=settings.AUTH_USER_MODEL),
        ),
    ]
